version: '3.8'
services:
  web:
    build: .
    container_name: app
    restart: always
    command: gunicorn wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - .:/usr/src/app/
    ports:
      - "80:8000"
    env_file:
      - .env